module.exports = {
  "navigaorbar":{
    flexDirection:'row',
    justifyContent:'space-between',
    marginTop:40,
    marginBottom:20
  },
  "carddetail":{
    paddingLeft:20,
    paddingTop:10,
    paddingBottom:10,
    backgroundColor:'#f4f2f2',
    justifyContent:'center'
  },
  "cancelText":{
    fontSize:16,
    color:'#fb3353',
    textAlign:'left'
  },
  "doneText":{
    fontSize:16,
    color:'#fb3353',
    textAlign:'right'
  },
  "tripTextView":{
    flex:1,
    alignItems:'center',
    justifyContent:'center'
  },
  "tripText":{
    fontSize:20,
    textAlign:'center'
  },
  "bodyView":{
    flex:1,
    borderTopWidth:5,
    borderTopColor:'#c9c6c6',
  },
  "cardnumber":{
    marginTop:20,
    alignItems:'center',
    borderBottomWidth:1,
    borderBottomColor:'#000000',
    marginLeft:20,marginRight:20,
    justifyContent:'space-between',
    flexDirection:'row'
  },
  "cardholder":{
    marginTop:20,
    justifyContent:'center',
    borderBottomWidth:1,
    borderBottomColor:'#000000',
    marginLeft:20,
    marginRight:20,
  },
  "dateView":{
    marginTop:20,
    marginLeft:20,
    marginRight:20,
    flexDirection:'row',
    justifyContent:'space-between'
  },
  "invaliddate":{
    flex:1,
    textAlign:'right',
    marginRight:10,
    color:'#fb3353',
    fontSize:12
  },
  "billingaddress":{
    marginTop:20,
    paddingLeft:20,
    paddingTop:10,
    paddingBottom:10,
    backgroundColor:'#f4f2f2',
    justifyContent:'center'
  },
  "billingphone":{
    marginTop:20,
    justifyContent:'center',
    borderBottomWidth:1,
    borderBottomColor:'#000000',
    marginLeft:20,
    marginRight:20,
  },
  "address":{
    marginTop:20,
    justifyContent:'center',
    borderBottomWidth:1,
    borderBottomColor:'#000000',
    marginLeft:20,
    marginRight:20,
  },
  "postcode":{
    marginTop:20,
    marginLeft:20,
    marginRight:20,
    flexDirection:'row',
    justifyContent:'space-between'
  },
  "state":{
    flex:1,
    marginRight:10,
    alignItems:'center',
    borderBottomWidth:1,
    borderBottomColor:'#fb3353',
    justifyContent:'space-between',
    flexDirection:'row'
  },
  "stateView":{
    marginTop:20,
    marginLeft:20,
    marginRight:20,
    flexDirection:'row',
    justifyContent:'space-between'
  },
  "postText":{
    flex:1,
    marginRight:10,
    borderBottomWidth:1,
    borderBottomColor:'#000000'
  },
}
