module.exports = {
  "ticketView":{
    marginTop:10,
    paddingLeft:20,
    paddingRight:20,
    flexDirection:'row',
    justifyContent:'space-between'
  },
  "priceText":{
    backgroundColor:'transparent',
    fontSize:30
  },
  "priceValue":{
    marginTop:5,
    backgroundColor:'transparent',
    fontSize:16
  },
  "forandbuyView":{
    marginTop:10,
    paddingLeft:20,
    paddingRight:20,
    flexDirection:'row',
    justifyContent:'space-between'
  },
  "buypack":{
    marginTop:10,
    height:40,
    width:150,
    borderRadius:20,
    backgroundColor:'#fb3353',
    alignItems:'center',
    justifyContent:'center'
  },
  "headerView":{
    marginTop:40,
    marginBottom:20,
    alignItems:'center',
    flexDirection:'row',
    justifyContent:'space-between'
  },
  "selectService":{
    borderBottomColor:'#c4babc',
    borderBottomWidth:1,
    marginLeft:30,
    marginRight:30,
    marginTop:15,
    paddingBottom:15,
    alignItems:'center',
    justifyContent:'center'
  },
  "minusButton":{
    marginTop:10,
    width:50,
    height:50,
    borderRadius:25,
    borderWidth:1,
    borderColor:'#fb3353',
    alignItems:'center',
    justifyContent:'center'
  },
  "plusButton":{
    marginTop:10,
    width:50,
    height:50,
    borderRadius:25,
    borderWidth:1,
    borderColor:'#fb3353',
    alignItems:'center',
    justifyContent:'center'
  },
  "purchageButton":{
    height:40,
    borderRadius:20,
    backgroundColor:'#fb3353',
    alignItems:'center',
    justifyContent:'center'
  },
  "onlyTextColor":{
    color:'#ffffff',
  },
  "createAccountButton":{
    marginTop:30,
    marginLeft:20,
    alignItems:'center',
    justifyContent:'center'
  },
  "createAccountText":{
    color:'#ffffff',
    backgroundColor:'transparent',
    fontSize:16,
  },
  "loginFacebookButton":{
    marginTop:30,
    marginLeft:20,
    alignItems:'center',
    justifyContent:'center'
  },
}
