module.exports = {
  "imageStyle":{
    flex: 1,
    width: null,
    height: null,
    resizeMode: 'cover',
  },
  "firstName":{
    marginTop:45,
    paddingBottom:5,
    flexDirection:'row',
    borderBottomWidth:1,
    borderBottomColor:'#ffffff',
    marginLeft:20,
    marginRight:20
  },
  "mark":{
    alignItems:'center',
    marginTop:100,
  },
  "textInput":{
    height:15,
    marginLeft:10,
    color:'#ffffff',
    flex:1
  },
  "textInputView":{
    marginTop:45,
    paddingBottom:5,
    flexDirection:'row',
    borderBottomWidth:1,
    borderBottomColor:'#ffffff',
    marginLeft:20,marginRight:20
  },
  "signButton":{
    marginTop:30,
    borderRadius:25,
    height:50,
    marginLeft:20,
    marginRight:20,
    backgroundColor:'#fb3353',
    alignItems:'center',
    justifyContent:'center'
  },
  "byCreate":{
    marginTop:30,
    marginLeft:20,
    alignItems:'center',
    justifyContent:'center'
  },
  "backLogin":{
    marginTop:30,
    marginLeft:20,
    alignItems:'center',
    justifyContent:'center'
  },
  "pinInput":{
    height:15,
    marginLeft:10,
    color:'#ffffff',
    flex:1
  },
  "forgotPin":{
    color:'#ffffff',
    backgroundColor:'transparent',
    fontSize:10,
  },
  "loginButton":{
    marginTop:40,
    borderRadius:25,
    height:50,
    marginLeft:20,
    marginRight:20,
    backgroundColor:'#fb3353',
    alignItems:'center',
    justifyContent:'center'
  },
  "onlyTextColor":{
    color:'#ffffff',
  },
  "createAccountButton":{
    marginTop:30,
    marginLeft:20,
    alignItems:'center',
    justifyContent:'center'
  },
  "createAccountText":{
    color:'#ffffff',
    backgroundColor:'transparent',
    fontSize:16,
  },
  "loginFacebookButton":{
    marginTop:30,
    marginLeft:20,
    alignItems:'center',
    justifyContent:'center'
  },
  "smallText":{
    color:'#ffffff',
    backgroundColor:'transparent',
    fontSize:12,
  },
  "normalText":{
    color:'#ffffff',
    backgroundColor:'transparent',
    fontSize:16,
  },
}
