module.exports = {
  "markView":{
    alignItems:'center',
    marginTop:150,
  },
  "explainText1":{
    textAlign:'center',
    marginTop:40,
    backgroundColor:'transparent',
    color:'#ffffff',
    fontSize:16
  },
  "explainText2":{
    textAlign:'center',
    backgroundColor:'transparent',
    color:'#ffffff',
    fontSize:14
  },
  "emailView":{
    marginTop:120,
    paddingBottom:5,
    flexDirection:'row',
    borderBottomWidth:1,
    borderBottomColor:'#ffffff',
    marginLeft:20,
    marginRight:20
  },
  "emailInput":{
    height:15,
    marginLeft:10,
    color:'#ffffff',
    flex:1
  },
  "resetView":{
    marginTop:30,
    borderRadius:25,
    height:50,
    marginLeft:20,
    marginRight:20,
    backgroundColor:'#fb3353',
    alignItems:'center',
    justifyContent:'center'
  },
  "goback":{
    marginTop:30,
    marginLeft:20,
    alignItems:'center',
    justifyContent:'center'
  },
  "forgotPin":{
    color:'#ffffff',
    backgroundColor:'transparent',
    fontSize:10,
  },
  "loginButton":{
    marginTop:40,
    borderRadius:25,
    height:50,
    marginLeft:20,
    marginRight:20,
    backgroundColor:'#fb3353',
    alignItems:'center',
    justifyContent:'center'
  },
  "onlyTextColor":{
    color:'#ffffff',
  },
  "createAccountButton":{
    marginTop:30,
    marginLeft:20,
    alignItems:'center',
    justifyContent:'center'
  },
  "createAccountText":{
    color:'#ffffff',
    backgroundColor:'transparent',
    fontSize:16,
  },
  "loginFacebookButton":{
    marginTop:30,
    marginLeft:20,
    alignItems:'center',
    justifyContent:'center'
  },
}
