module.exports = {
  "totalView":{
    flex:1,
    justifyContent:'space-between'
  },
  "mark":{
    flex:1,
    alignItems:'center',
    justifyContent:'center'
  },
  "email":{
    paddingBottom:5,
    flexDirection:'row',
    borderBottomWidth:1,
    borderBottomColor:'#ffffff',
    marginLeft:20,
    marginRight:20
  },
  "emailText":{
    backgroundColor:'transparent',
    color:'#ffffff'
  },
  "emailInput":{
    height:15,
    marginLeft:10,
    color:'#ffffff',
    flex:1
  },
  "pin":{
    marginTop:50,
    paddingBottom:5,
    flexDirection:'row',
    borderBottomWidth:1,
    borderBottomColor:'#ffffff',
    marginLeft:20,
    marginRight:20
  },
  "pinText":{
    backgroundColor:'transparent',
    color:'#ffffff'
  },
  "pinInput":{
    height:15,
    marginLeft:10,
    color:'#ffffff',
    flex:1
  },
  "forgotPin":{
    color:'#ffffff',
    backgroundColor:'transparent',
    fontSize:10,
  },
  "loginButton":{
    marginTop:40,
    borderRadius:25,
    height:50,
    marginLeft:20,
    marginRight:20,
    backgroundColor:'#fb3353',
    alignItems:'center',
    justifyContent:'center'
  },
  "onlyTextColor":{
    color:'#ffffff',
  },
  "createAccountButton":{
    marginTop:30,
    marginLeft:20,
    alignItems:'center',
    justifyContent:'center'
  },
  "createAccountText":{
    color:'#ffffff',
    backgroundColor:'transparent',
    fontSize:16,
  },
  "loginFacebookButton":{
    marginTop:30,
    marginLeft:20,
    alignItems:'center',
    justifyContent:'center'
  },
}
