module.exports = {
  "headerView":{
    flex:1.2,
    backgroundColor:'#fb3353',
  },
  "flexheader":{
    justifyContent:'space-between',
    marginTop:40,
    flexDirection:'row'
  },
  "close":{
    alignItems:"flex-end",
    marginRight:20
  },
  "headerText":{
    textAlign:'center',
    color:'#ffffff',
    marginTop:10,
    fontSize:20
  },
  "listView":{
    width:50,
    alignItems:'center',
  },
  "listLink":{
    flex:1,
    paddingBottom:25,
    marginLeft:20,
    borderBottomWidth:1,
    borderBottomColor:'#000000'
  },
  "listLinkText":{
    flexDirection:'row',
    paddingRight:20,
    justifyContent:'space-between'
  },
  "eachView":{
    flexDirection:'row',
    marginTop:25,
  },
  "bookTrip":{
    marginBottom:20,
    marginLeft:30,
    marginRight:30,
    height:50,
    borderRadius:25,
    backgroundColor:'#fb3353',
    alignItems:'center',
    justifyContent:'center'
  },
  "forgotPin":{
    color:'#ffffff',
    backgroundColor:'transparent',
    fontSize:10,
  },
  "loginButton":{
    marginTop:40,
    borderRadius:25,
    height:50,
    marginLeft:20,
    marginRight:20,
    backgroundColor:'#fb3353',
    alignItems:'center',
    justifyContent:'center'
  },
  "onlyTextColor":{
    color:'#ffffff',
  },
  "createAccountButton":{
    marginTop:30,
    marginLeft:20,
    alignItems:'center',
    justifyContent:'center'
  },
  "createAccountText":{
    color:'#ffffff',
    backgroundColor:'transparent',
    fontSize:16,
  },
  "loginFacebookButton":{
    marginTop:30,
    marginLeft:20,
    alignItems:'center',
    justifyContent:'center'
  },
}
