module.exports = {
  "navigaorbar":{
    flexDirection:'row',
    justifyContent:'space-between',
    marginTop:40,
    marginBottom:20
  },
  "headerView":{
    flexDirection:'row',
    justifyContent:'space-between',
    marginTop:40,
    marginBottom:20,
  },
  "backText":{
    fontSize:16,
    color:'#fb3353',
    textAlign:'left',
    marginLeft:10,
  },
  "visa":{
    paddingTop:20,
    paddingBottom:20,
    flexDirection:'row',
    justifyContent:'space-between',
    backgroundColor:'#fb3353'
  },
  "tickets":{
    marginTop:250,
    flexDirection:'row',
    justifyContent:'space-between',
    marginLeft:20,
    marginRight:20
  },
  "total":{
    marginLeft:20,
    marginRight:20,
    height:10,
    borderLeftWidth:1,
    borderLeftColor:'#000000',
    borderBottomWidth:1,
    borderBottomColor:'#000000'
  },
  "totalView":{
    marginTop:20,
    flexDirection:'row',
    justifyContent:'space-between',
    marginLeft:20,
    marginRight:20
  },
  "confirmButton":{
    height:50,
    borderRadius:25,
    backgroundColor:'#fb3353',
    alignItems:'center',
    justifyContent:'center'
  },
}
