module.exports = {
  "navigaorbar":{
    flexDirection:'row',
    justifyContent:'space-between',
    marginTop:40,
    marginBottom:20
  },
  "header":{
    flexDirection:'row',
    justifyContent:'space-between',
    marginTop:40,
    marginBottom:20,
  },
  "backText":{
    fontSize:16,
    color:'#fb3353',
    textAlign:'left',
    marginLeft:10,
  },
  "firstname":{
    marginTop:20,
    flexDirection:'row',
    justifyContent:'space-between',
    marginLeft:40,
    marginRight:40,
  },
  "eachView":{
    marginTop:40,
    flexDirection:'row',
    justifyContent:'space-between',
    marginLeft:40,
    marginRight:40,
  },
  "security":{
    marginTop:40,
    flexDirection:'row',
    justifyContent:'space-between',
    marginLeft:40,
    marginRight:40,
  },
  "signout":{
    height:50,
    borderRadius:25,
    borderWidth:1,
    borderColor:'#fb3353',
    justifyContent:'center',
    alignItems:'center'
  },
  "bookTripButtonView":{
    marginBottom:30,
    paddingLeft:40,
    paddingRight:40,
  },
  "bookTripButton":{
    borderRadius:25,
    height:50,
    alignItems:'center',
    justifyContent:'center',
    backgroundColor:'#fb3353'
  },
}
