module.exports = {
  "navigaorbar":{
    flexDirection:'row',
    justifyContent:'space-between',
    marginTop:40,
    marginBottom:20
  },
  "backView":{
    flex:1,
    flexDirection:'row',
    marginLeft:20,
    marginTop:5
  },
  "text1":{
    fontSize:18,
    color:'#fb3353'
  },
  "text2":{
    fontSize:18,
    color:'#fb3353',
    marginLeft:5
  },
  "tripTextView":{
    flex:1,
    alignItems:'center',
    justifyContent:'center'
  },
  "tripText":{
    fontSize:20,
    textAlign:'center'
  },
  "bodyView":{
    flex:1,
    borderTopWidth:3,
    borderTopColor:'#f4f2f2',
  },
  "segemantView":{
    height:38,
    borderWidth:1,
    borderRadius:19,
    borderColor:'#ff0000',
    marginLeft:40,
    marginTop:10,
    marginRight:40,
  },
  "segmentTap":{
    height:36,
    backgroundColor:'transparent',
    borderColor:'transparent'
  },
  "eachView":{
    paddingLeft:20,
    paddingRight:20,
    paddingTop:30,
    paddingBottom:10,
    flexDirection:'row',
    justifyContent:'space-between',
    alignItems:'center'
  },
  "commonText":{
      color:'#000000',
      backgroundColor:'transparent',
      fontSize:16,
    },
  "smallText":{
    fontSize:12,
    marginTop:10
  },
  "bookTripButtonView":{
    marginBottom:30,
    paddingLeft:40,
    paddingRight:40,
  },
  "bookTripButton":{
    borderRadius:25,
    height:50,
    alignItems:'center',
    justifyContent:'center',
    backgroundColor:'#fb3353'
  },
}
